version: 2
updates:
  - package-ecosystem: "npm" # Change this to the appropriate ecosystem
    directory: "/" # Ensure this is the correct directory where package.json is located
    schedule:
      interval: "weekly"
